name: zip Checkmarx One

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.1.6
        with:
          repository: 'Checkmarx/ast-cli'

      - name: Create ZIP of Checkmarx AST CLI 🗜️
        run: |
          zip -r ast-cli.zip ./ast-cli
          
      - name: Upload ZIP to JFrog Artifactory 🐙
        run: |
          curl -ukirashiraishi@gmail.com:${{ secrets.JFROG_PASSWORD }} -T ./ast-cli.zip "https://trial4snq1g.jfrog.io/artifactory/checkmarx-cli-generic-local/ast-cli-latest.zip"
